spring:
  application:
    name: account-processing

  kafka:
    consumer:
      group-id: "default"

  config:
    import:
      optional:application-secret.yaml

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

    jpa:
      show-sql: true
      hibernate:
        ddl-auto: validate

    liquibase:
      enabled: true

server:
  port: 8081

transaction:
  max-count: 2
  period:
    start-days-offset: 10
    end-days-offset: 10