spring:
  application:
    name: client-processing

  kafka:
    consumer:
      group-id: "default"

  config:
    import:
      optional:application-secret.yaml

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

    jpa:
      show-sql: true
      hibernate:
        ddl-auto: validate

    liquibase:
      enabled: true

server:
  port: 8084

#limit:
#  time:
#    method-execution: 100
#    cache-storage: 10000

#sapegin:
#  aspect:
#    metric:
#      enabled: true
#      time-limit: 200
#    cached:
#      enabled: true
#      time-limit: 10000
#    income-request:
#      enabled: true
#    outcome-request:
#      enabled: true
#    log-datasource:
#      enabled: true

jwt:
  secret:
    access: ${JWT_ACCESS_SECRET}
    refresh: ${JWT_REFRESH_SECRET}