spring:
  application:
    name: client-processing

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/client_processing_db
    username: postgres
    password: postgres

    jpa:
      show-sql: true
      hibernate:
        ddl-auto: validate

#    liquibase:
#      enabled: true

server:
  port: 8082
